StarTrekDVD.o:  StarTrekDVD.cpp StarTrekDVD.h
	g++ -g -Wall -std=c++11 -c StarTrekDVD.cpp

StarTrekDVDdriver:  StarTrekDVD.o StarTrekDVDdriver.o
	g++ -g -Wall -std=c++11 -o StarTrekDVDdriver StarTrekDVD.o StarTrekDVDdriver.o

StarTrekDVDdriver.o: StarTrekDVD.o StarTrekDVD.cpp
	g++ -g -Wall -std=c++11 -c StarTrekDVDdriver.cpp